export default function createMercadoPagoOrder(exists = false) {
  let response = {
    ok: true,
    data: {
      order: {
        id: 5,
        paymentId: 1324207593,
        userId: 1,
        paymentDate: "2024-01-30T15:54:12.731Z",
        payerEmail: "beautipol.alpha.1@gmail.com",
        payerDocumentType: "DNI",
        payerDocumentNumber: "46822739",
        installments: 1,
        issuerId: "12347",
        paymentMethodId: "master",
        token: "b33409724bf9c2059044d16856414cb8",
        status: "created",
        amount: "194",
        shippingMethod: "regular",
        shippingName: "Beautipol Alpha",
        shippingAddress: "Av. Larco 1010, Miraflores",
        shippingCity: "Lima",
        shippingRegion: "Lima",
        shippingPhoneNumber: "+51 123909090",
        billingName: "Beautipol Alpha",
        billingAddress: "Av. Larco 1010, Miraflores",
        billingCity: "Lima",
        billingRegion: "Lima",
        billingPhoneNumber: "+51 123909090",
        createdAt: "2024-06-21T23:21:01.520Z",
        updatedAt: "2024-06-21T23:21:01.861Z",
      },
      payment: {
        id: 1324207593,
        date_created: "2024-06-21T15:46:42.490-04:00",
        date_approved: "2024-06-21T15:46:42.742-04:00",
        date_last_updated: "2024-06-21T15:46:42.742-04:00",
        date_of_expiration: null,
        money_release_date: "2024-06-21T15:46:42.742-04:00",
        money_release_status: "released",
        operation_type: "regular_payment",
        issuer_id: "1056",
        payment_method_id: "visa",
        payment_type_id: "credit_card",
        payment_method: {
          id: "visa",
          type: "credit_card",
          issuer_id: "1056",
          data: {
            routing_data: {
              merchant_account_id: "462540702",
            },
          },
        },
        status: "approved",
        status_detail: "accredited",
        currency_id: "PEN",
        description: "Product payment",
        live_mode: false,
        sponsor_id: null,
        authorization_code: "229549003",
        money_release_schema: null,
        taxes_amount: 0,
        counter_currency: null,
        brand_id: null,
        shipping_amount: 0,
        build_version: "3.57.1",
        pos_id: null,
        store_id: null,
        integrator_id: null,
        platform_id: null,
        corporation_id: null,
        payer: {
          identification: {
            number: "32659430",
            type: "DNI",
          },
          entity_type: null,
          phone: {
            number: null,
            extension: null,
            area_code: null,
          },
          last_name: null,
          id: "1866717253",
          type: null,
          first_name: null,
          email: "test_user_80507629@testuser.com",
        },
        collector_id: 276125154,
        marketplace_owner: null,
        metadata: {},
        additional_info: {
          available_balance: null,
          nsu_processadora: null,
          authentication_code: null,
        },
        order: {},
        external_reference: null,
        transaction_amount: 46,
        transaction_amount_refunded: 0,
        coupon_amount: 0,
        differential_pricing_id: null,
        financing_group: null,
        deduction_schema: null,
        installments: 1,
        transaction_details: {
          payment_method_reference_id: null,
          acquirer_reference: null,
          net_received_amount: 42.65,
          total_paid_amount: 46,
          overpaid_amount: 0,
          external_resource_url: null,
          installment_amount: 46,
          financial_institution: null,
          payable_deferral_period: null,
        },
        fee_details: [
          {
            type: "mercadopago_fee",
            amount: 3.35,
            fee_payer: "collector",
          },
        ],
        charges_details: [
          {
            id: "1324207593-001",
            name: "mercadopago_fee",
            type: "fee",
            accounts: {
              from: "collector",
              to: "mp",
            },
            client_id: 0,
            date_created: "2024-06-21T15:46:42.000-04:00",
            last_updated: "2024-06-21T15:46:42.000-04:00",
            amounts: {
              original: 3.35,
              refunded: 0,
            },
            metadata: {},
            reserve_id: null,
            refund_charges: [],
          },
        ],
        captured: true,
        binary_mode: false,
        call_for_authorize_id: null,
        statement_descriptor: null,
        card: {
          id: null,
          first_six_digits: "423564",
          last_four_digits: "5682",
          expiration_month: 11,
          expiration_year: 2025,
          date_created: "2024-06-21T15:46:42.000-04:00",
          date_last_updated: "2024-06-21T15:46:42.000-04:00",
          country: null,
          tags: null,
          cardholder: {
            name: "Rel Guzman",
            identification: {
              number: "36822759",
              type: "DNI",
            },
          },
        },
        notification_url: null,
        refunds: [],
        processing_mode: "aggregator",
        merchant_account_id: null,
        merchant_number: null,
        point_of_interaction: {
          type: "UNSPECIFIED",
          business_info: {
            unit: "online_payments",
            sub_unit: "default",
            branch: "Merchant Services",
          },
        },
        accounts_info: null,
        tags: null,
      },
    },
  };
  return response;
}
